spring:
  datasource:
    url: "jdbc:sqlite://${project.basedir}/sterling.db"
  flyway:
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    cleanDisabled: false
  thymeleaf:
    cache: false
    check-template: true
#    check if we want enable-spring-el-compiler ?
    enable-spring-el-compiler: false
    produce-partial-output-while-processing: true
#    prefix: classpath:/templates/

